package jef.database.routing.jdbc;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

public interface SQLExecutor {
	public void setFetchSize(int fetchSize);
	public void setMaxResults(int maxRows);
	public void setQueryTimeout(int queryTimeout);
	
	public UpdateReturn executeUpdate(int generateKeys,int[] returnIndex,String[] returnColumns,List<ParameterContext> params) throws SQLException;
	public BatchReturn executeBatch(int autoGeneratedKeys, int[] columnIndexes, String[] columnNames, List<List<ParameterContext>> params) throws SQLException;
	public ResultSet getResultSet(int resultType,int resultConcurrency,int resultHoldability,List<ParameterContext> params) throws SQLException;
}
