CREATE FUNCTION REPLACE(STR VARCHAR(255), OLD VARCHAR(100), NEW VARCHAR(100)) RETURNS 
   VARCHAR(255) PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA EXTERNAL NAME 'org.apache.commons.lang.StringUtils.replace';
   
CREATE FUNCTION USR_LEFTPAD(STR VARCHAR(255), LEN INTEGER, PADCHAR VARCHAR(64)) RETURNS 
   VARCHAR(255) PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA EXTERNAL NAME 'org.apache.commons.lang.StringUtils.leftPad';
   
CREATE FUNCTION USR_RIGHTPAD(STR VARCHAR(255), LEN INTEGER, PADCHAR VARCHAR(64)) RETURNS 
   VARCHAR(255) PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA EXTERNAL NAME 'org.apache.commons.lang.StringUtils.rightPad';
   
CREATE FUNCTION USR_TRUNC(F DOUBLE, TRC INTEGER) RETURNS 
   DOUBLE PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA EXTERNAL NAME 'jef.tools.MathUtils.trunc';
   
CREATE FUNCTION USR_TRANSLATE(STR VARCHAR(255), OLD VARCHAR(50), NEW VARCHAR(50)) RETURNS 
   VARCHAR(255) PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA EXTERNAL NAME 'org.apache.commons.lang.StringUtils.replaceChars';
   
   