package org.googlecode.jef.spring.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import jef.codegen.support.NotModified;
/**
 * This class was generated by JEF according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(name="t_user")
public class TUser extends DataObject{


	@Column(name="user_name",columnDefinition="Varchar",length=255)
	private String userName;

	@Column(name="score",precision=10,columnDefinition="NUMBER")
	private Long score;

	@Column(name="password",columnDefinition="Varchar",length=255)
	private String password;

	public void setUserName(String obj){
		this.userName = obj;
	}

	public String getUserName(){
		return userName;
	}

	public void setScore(Long obj){
		this.score = obj;
	}

	public Long getScore(){
		return score;
	}

	public void setPassword(String obj){
		this.password = obj;
	}

	public String getPassword(){
		return password;
	}

	public TUser(){
	}


public enum Field implements jef.database.Field{userName,score,password}
}