package jef.orm.onetable.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import jef.database.DataObject;

/**
 * This class was generated by JEF according to the table in database. You also
 * need to modify the type of primary key field, to strategy you own.
 * 
 */
@Entity
@Table(name = "ca_asset")
public class CaAsset extends DataObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Asset ID
	 */
	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE) 
	@Column(name = "asset_id", precision = 6, columnDefinition = "NUMBER", nullable = false)
	private int assetId;

	/**
	 * A unique identifier of account.
	 */
	@Column(name = "acct_id", precision = 14, columnDefinition = "NUMBER")
	private Long acctId;

	/**
	 * Asset type: 0- fund(account book), 1- credit limit, 2- bonus, 3- bank
	 * capital, 4- free resource, 5 - cheque.
	 */
	@Column(name = "ASSET_TYPE", precision = 8, columnDefinition = "NUMBER")
	private Integer assetType;

	private String normal;
	
	@Column(name = "VALID_DATE",columnDefinition="Date")
	private Date  thedate;
	
	public String getNormal() {
		return normal;
	}

	public void setNormal(String normal) {
		this.normal = normal;
	}

	public Date getThedate() {
		return thedate;
	}

	public void setThedate(Date thedate) {
		this.thedate = thedate;
	}

	public CaAsset() {
	}


	public void setAssetId(int assetId) {
		this.assetId = assetId;
	}

	public CaAsset(String normal) {
		this.normal=normal;
	}
	
	public int getAssetId() {
		return assetId;
	}


	public Long getAcctId() {
		return acctId;
	}

	public void setAcctId(Long acctId) {
		this.acctId = acctId;
	}

	public Integer getAssetType() {
		return assetType;
	}

	public void setAssetType(Integer assetType) {
		this.assetType = assetType;
	}


	public enum Field implements jef.database.Field {
		acctId, assetId, assetType,thedate,normal
	}
}
