package jef.orm.postgresql.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import jef.codegen.support.NotModified;
import jef.database.DataObject;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(name="test_columntypes_common")
public class TestColumntypesCommon extends DataObject{


	@Column(name="smallintfield",precision=5,columnDefinition="NUMBER",nullable=false)
	private int smallintfield;

	@Column(name="int2field",precision=5,columnDefinition="NUMBER")
	private Integer int2field;

	@Column(name="intfield2",precision=10,columnDefinition="NUMBER")
	private Long intfield2;

	@Column(name="bigintfield",precision=19,columnDefinition="NUMBER")
	private Long bigintfield;

	@Column(name="decimalfield",scale=4,precision=131089,columnDefinition="NUMBER")
	private Double decimalfield;

	@Column(name="numericfield",scale=4,precision=131089,columnDefinition="NUMBER")
	private Double numericfield;

	@Column(name="numericfield2",scale=2,precision=5,columnDefinition="NUMBER")
	private Float numericfield2;

	@Column(name="realfield",scale=8,precision=8,columnDefinition="NUMBER")
	private Float realfield;

	@Column(name="floatfield",scale=8,precision=8,columnDefinition="NUMBER",nullable=false)
	private Float floatfield;

	@Column(name="doublefield",scale=17,precision=17,columnDefinition="NUMBER",nullable=false)
	private Double doublefield;

	@Column(name="doublefield2",scale=17,precision=17,columnDefinition="NUMBER")
	private Double doublefield2;

	@Column(name="serialfield",precision=10,columnDefinition="NUMBER",nullable=false)
	private long serialfield;

	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="serialfield2",precision=19,columnDefinition="NUMBER",nullable=false)
	private long serialfield2;

	@Column(name="varcharfield1",columnDefinition="Varchar",length=255)
	private String varcharfield1;

	@Column(name="varcharfield2",columnDefinition="Varchar",length=2147483647)
	private String varcharfield2;

	@Column(name="charfield1",columnDefinition="Char",length=2)
	private String charfield1;

	@Column(name="charfield2",columnDefinition="Char",length=1)
	private String charfield2;

	@Column(name="booleanfield1",columnDefinition="Boolean",nullable=false)
	private Boolean booleanfield1;

	@Column(name="booleanfield2",columnDefinition="Boolean")
	private Boolean booleanfield2;

	@Column(name="datefield",columnDefinition="Date")
	private Date datefield;

	@Column(name="timestampfield1",columnDefinition="TimeStamp")
	private Date timestampfield1;

	@Column(name="timestampfield2",columnDefinition="TimeStamp")
	private Date timestampfield2;

	@Column(name="timefield1",columnDefinition="TimeStamp")
	private Date timefield1;

	@Column(name="timefield2",columnDefinition="TimeStamp")
	private Date timefield2;

	@Lob
	@Column(name="binaryfield",columnDefinition="Blob")
	private byte[] binaryfield;

	@Lob
	@Column(name="textfield",columnDefinition="Clob")
	private String textfield;

	public void setSmallintfield(int obj){
		this.smallintfield = obj;
	}

	public int getSmallintfield(){
		return smallintfield;
	}

	public void setInt2field(Integer obj){
		this.int2field = obj;
	}

	public Integer getInt2field(){
		return int2field;
	}

	public void setIntfield2(Long obj){
		this.intfield2 = obj;
	}

	public Long getIntfield2(){
		return intfield2;
	}

	public void setBigintfield(Long obj){
		this.bigintfield = obj;
	}

	public Long getBigintfield(){
		return bigintfield;
	}

	public void setDecimalfield(Double obj){
		this.decimalfield = obj;
	}

	public Double getDecimalfield(){
		return decimalfield;
	}

	public void setNumericfield(Double obj){
		this.numericfield = obj;
	}

	public Double getNumericfield(){
		return numericfield;
	}

	public void setNumericfield2(Float obj){
		this.numericfield2 = obj;
	}

	public Float getNumericfield2(){
		return numericfield2;
	}

	public void setRealfield(Float obj){
		this.realfield = obj;
	}

	public Float getRealfield(){
		return realfield;
	}

	public void setFloatfield(Float obj){
		this.floatfield = obj;
	}

	public Float getFloatfield(){
		return floatfield;
	}

	public void setDoublefield(Double obj){
		this.doublefield = obj;
	}

	public Double getDoublefield(){
		return doublefield;
	}

	public void setDoublefield2(Double obj){
		this.doublefield2 = obj;
	}

	public Double getDoublefield2(){
		return doublefield2;
	}

	public void setSerialfield(long obj){
		this.serialfield = obj;
	}

	public long getSerialfield(){
		return serialfield;
	}

	public void setSerialfield2(long obj){
		this.serialfield2 = obj;
	}

	public long getSerialfield2(){
		return serialfield2;
	}

	public void setVarcharfield1(String obj){
		this.varcharfield1 = obj;
	}

	public String getVarcharfield1(){
		return varcharfield1;
	}

	public void setVarcharfield2(String obj){
		this.varcharfield2 = obj;
	}

	public String getVarcharfield2(){
		return varcharfield2;
	}

	public void setCharfield1(String obj){
		this.charfield1 = obj;
	}

	public String getCharfield1(){
		return charfield1;
	}

	public void setCharfield2(String obj){
		this.charfield2 = obj;
	}

	public String getCharfield2(){
		return charfield2;
	}

	public void setBooleanfield1(Boolean obj){
		this.booleanfield1 = obj;
	}

	public Boolean isBooleanfield1(){
		return booleanfield1;
	}

	public void setBooleanfield2(Boolean obj){
		this.booleanfield2 = obj;
	}

	public Boolean isBooleanfield2(){
		return booleanfield2;
	}

	public void setDatefield(Date obj){
		this.datefield = obj;
	}

	public Date getDatefield(){
		return datefield;
	}

	public void setTimestampfield1(Date obj){
		this.timestampfield1 = obj;
	}

	public Date getTimestampfield1(){
		return timestampfield1;
	}

	public void setTimestampfield2(Date obj){
		this.timestampfield2 = obj;
	}

	public Date getTimestampfield2(){
		return timestampfield2;
	}

	public void setTimefield1(Date obj){
		this.timefield1 = obj;
	}

	public Date getTimefield1(){
		return timefield1;
	}

	public void setTimefield2(Date obj){
		this.timefield2 = obj;
	}

	public Date getTimefield2(){
		return timefield2;
	}

	public void setBinaryfield(byte[] obj){
		this.binaryfield = obj;
	}

	public byte[] getBinaryfield(){
		return binaryfield;
	}

	public void setTextfield(String obj){
		this.textfield = obj;
	}

	public String getTextfield(){
		return textfield;
	}

	public TestColumntypesCommon(){
	}

	public TestColumntypesCommon(long serialfield2){
		this.serialfield2 = serialfield2;
	}


public enum Field implements jef.database.Field{smallintfield,int2field,intfield2,bigintfield,decimalfield,numericfield,numericfield2,realfield,floatfield,doublefield,doublefield2,serialfield,serialfield2,varcharfield1,varcharfield2,charfield1,charfield2,booleanfield1,booleanfield2,datefield,timestampfield1,timestampfield2,timefield1,timefield2,binaryfield,textfield}
}
